# Site settings
title: Lorenzo Feroleto's blog
email: you@example.com
description: >-
  Collections of technical articles and thoughts.
baseurl: "" # the subpath of your site, e.g. /blog (leave empty for user site)
url: "https://thedevbirb.github.io"
author: Lorenzo Feroleto
twitter_username:
github_username:

# Build settings
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude these from Jekyll (Obsidian noise)
exclude:
  - .obsidian
  - templates
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github

# Default front matter for posts
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
